#!/bin/sh
# Registers the merge drivers named in .gitattributes.
#
# Git deliberately ignores merge drivers defined in tracked config -- a driver
# is arbitrary code, so cloning a repository must not be able to configure one.
# That means every clone, and every CI job that performs a merge, has to run
# this once. Idempotent; safe to re-run.
set -eu

cd "$(dirname "$0")/.."

if ! git rev-parse --git-dir >/dev/null 2>&1; then
    echo "setup-repo: not inside a git repository" >&2
    exit 1
fi

# `true` exits 0 leaving %A -- our version -- in place, which is what marks the
# path resolved. Nothing is discarded: the generated files this applies to are
# pure functions of src/js/**, which merges normally, and are regenerated by
# `make js` afterwards.
git config merge.keep-ours.name "keep the fork's version; regenerate afterwards"
git config merge.keep-ours.driver true

echo "setup-repo: merge driver 'keep-ours' registered"
