#!/bin/bash
#
# Downloads the Mozilla CA certificate bundle from curl.se, deflates it with
# zlib and converts it to a C source file with a compressed byte array for
# embedding in the binary. The declarations live in src/cacert.h (hand-written).
#
# Blob format (matches src/eval.c's tjs__read_bytecode / tjsc -z):
#   [uint32 LE raw_len][zlib stream]
# where raw_len is the length of the PEM text *including* a trailing NUL byte
# (mbedtls_x509_crt_parse requires a NUL-terminated buffer for PEM input).
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT="$PROJECT_DIR/src/cacert.c"

URL="https://curl.se/ca/cacert.pem"

command -v python3 >/dev/null 2>&1 || {
    echo "python3 is required to compress the CA bundle" >&2
    exit 1
}

echo "Downloading CA bundle from $URL ..."
PEM=$(curl -fsSL "$URL")

echo "Compressing and generating $OUTPUT ..."

TMP_PEM="$(mktemp)"
trap 'rm -f "$TMP_PEM"' EXIT
printf '%s\n' "$PEM" > "$TMP_PEM"

# Normalize to the same "line\n"-joined text the old plain-array generator
# produced (trailing NUL included), then deflate + emit the C source in one
# python3 pass.
python3 - "$TMP_PEM" "$OUTPUT" <<'PYEOF'
import sys
import zlib

in_path = sys.argv[1]
out_path = sys.argv[2]
with open(in_path, "rb") as f:
    pem = f.read()
# Match the historical char array contents: NUL-terminated.
raw = pem + b"\x00"
raw_len = len(raw)

compressed = zlib.compress(raw, 9)
blob = raw_len.to_bytes(4, "little") + compressed
blob_len = len(blob)

with open(out_path, "w") as f:
    f.write("/* clang-format off */\n\n")
    f.write("/*\n")
    f.write(" * Mozilla CA certificate bundle (miniz/zlib compressed).\n")
    f.write(" * Generated by scripts/update-ca-bundle.sh — do not edit manually.\n")
    f.write(" * Source: https://curl.se/ca/cacert.pem\n")
    f.write(" *\n")
    f.write(" * Blob format: [uint32 LE raw_len][zlib stream]; raw_len includes a\n")
    f.write(" * trailing NUL byte. Inflated lazily on first TLS use (see cacert.h).\n")
    f.write(" */\n\n")
    f.write('#include "cacert.h"\n\n')
    f.write(f"const uint32_t tjs_cacert_pem_gz_size = {blob_len};\n\n")
    f.write(f"const uint8_t tjs_cacert_pem_gz[{blob_len}] = {{\n")
    for i in range(0, blob_len, 8):
        chunk = blob[i:i + 8]
        f.write("    " + "".join(f"0x{b:02x}, " for b in chunk).rstrip() + "\n")
    f.write("};\n")

print(f"Done. raw PEM {len(pem)} bytes -> {raw_len} bytes (NUL-terminated) "
      f"-> {blob_len} bytes compressed ({100.0 * blob_len / raw_len:.1f}%).")
PYEOF
