/*
 * Mozilla CA certificate bundle.
 *
 * The data lives in cacert.c, generated by scripts/update-ca-bundle.sh, as a
 * miniz/zlib-compressed blob: [uint32 LE raw_len][zlib stream]. raw_len
 * includes a trailing NUL byte (mbedtls_x509_crt_parse requires a
 * NUL-terminated buffer for PEM input).
 *
 * Only built when BUILD_WITH_TLS and BUILD_WITH_BUNDLED_CA are both on
 * (TJS_HAVE_BUNDLED_CA defined).
 */

#ifndef TJS_CACERT_H
#define TJS_CACERT_H

#include <stddef.h>
#include <stdint.h>

typedef struct TJSRuntime TJSRuntime;

#ifdef TJS_HAVE_BUNDLED_CA

extern const uint8_t tjs_cacert_pem_gz[];
extern const uint32_t tjs_cacert_pem_gz_size;

/*
 * Lazily inflates the embedded CA bundle and caches the result on `qrt`
 * (owned by the runtime, freed at teardown). Inflate happens at most once
 * per runtime; returns NULL (and leaves *out_len untouched) on decompression
 * failure. The returned buffer is NUL-terminated; *out_len does NOT include
 * that trailing NUL (same convention as the old `sizeof(...) - 1` array).
 */
const char *tjs__cacert_pem(TJSRuntime *qrt, size_t *out_len);

#endif /* TJS_HAVE_BUNDLED_CA */

#endif /* TJS_CACERT_H */
